# languages : en, fr, nl, de
# what is an institution and an authority


#headers:
#  Accept-Language:
#    $ref: '#/components/headers/Accept-Language'

openapi: 3.0.0
servers:
  - url: api.wecitizens.be
    description: prod
  - url: api-test.wecitizens.be
    description: dev
info:
  title: WeCitizens API
  version: '0.3.0'
# Add a logo
x-tagGroups:
  - name: vote
    tags: [election, party, candidate]
  - name: gps # maybe find something more appropriate
    tags: [poll, survey, answer, match]
tags:
  - name: election
  - name: party
  - name: candidate
  - name: poll
  - name: survey
  - name: answer
  - name: match
paths:
  /vote/election/{key}:
    get:
      summary: an election
      tags: [election]
      parameters:
        - $ref: '#/components/parameters/key'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/election"
              examples:
                2014_be_regional:
                  value:
                    key: 2014_be_regional
                    type: be_regional
                    date: 2014-05-25
                    district_type: region
                    districts:
                      - key: be_ed
                        name: district_be_german_electoral_college
                      - key: be_ef
                        name: district_be_french_electoral_college
                      - key: be_en
                        name: district_be_dutch_electoral_college
                    i18n:
                      en:
                        district_be_regional_german_electoral_college: German electoral college
                        district_be_regional_french_electoral_college: French electoral college
                        district_be_regional_dutch_electoral_college: Dutch electoral college
  # /candidates/{id}:
  /vote/election/{main_election_key}/district/{district_key}: # not sure this is the best way to do it
    get:
      summary: a district election
      tags: [election]
      parameters:
        - $ref: '#/components/parameters/key'
        - $ref: '#/components/parameters/district_key'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/election"
              examples:
                compatibility:
                  value:
                    key: 2018_be_federal_chamber_of_representatives_fa
                    type: be_federal_chamber_of_representatives                    
                    date: 2017-05-17
                    main_election_key: 2018_be_federal_chamber_of_representatives
                    district_type: province # not sure it's the right term
                    district_key: be_fa
                    parties:
                      - key: be_bub
                        name: party_be_bub_name
                        candidates:
                          - order: 1
                            key: joeri_pen
                      - key: be_cdv
                        name: party_be_cdv_name
                        candidates:
                          - order: 1
                            key: servais_verherstraeten
                          - order: 2
                            key: nahima_lanjri
                        substitutes:
                          - order: 1
                            key: walter_schroons
                    candidates:
                      - key: servais_verherstraeten
                        name: Servais Verherstraeten
                        politician_id: politician_be_232
                      - key: nahima_lanjri
                        name: Nahima Lanjri
                        politician_id: politician_be_142
                      - key: walter_schroons
                        name: Walter Schroons
                        politician_id: politician_be_142
                    i18n:
                      en:
                        party_be_bub_name: B.U.B
                        party_be_cdv_name: CD&V
                        election_type_be_federal_chamber_of_representatives: Federal Chamber of Representatives # maybe already loaded
                      nl:
                        district_be_fa: Antwerp # maybe already loaded
                default: # TODO : adapt according to sample above 
                  value:
                    key: 2018_be_municipal_6850
                    main_election_key: 2018_be_municipal
                    district_key: be_municipal_6850
                    parties:
                      - key: cdnv
                        name: CDN-V
                        candidates:
                          - order: 1
                            key: o.wouters
                      - key: ecolo
                        name: Ecolo
                        candidates:
                          - order: 1
                            key: d.sum
                    candidates:
                      - key: o.wouters
                        fullname: Olivier Wouters
                      - key: d.sum
                        fullname: Daniel Sum
                        party_key: cdnv
  /vote/party/search:
    get:
      summary: search parties
      tags: [party]
      parameters:
        - $ref: '#/components/parameters/election_key'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/party_search_response"
              examples:
                default:
                  value:
                    data:
                      - key: be_bub
                        name: party_be_bub_name
                      - key: be_cdv
                        name: party_be_cdv_name
                    i18n:
                      en:
                        party_be_bub_name: B.U.B
                        party_be_cdv_name: CD&V                      
  /vote/candidate/search:
    get:
      summary: search candidates
      tags: [candidate]
      parameters:
        - $ref: '#/components/parameters/election_key'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/candidate_search_response"
              examples:
                default:
                  value:
                    data:
                      - key: servais_verherstraeten
                        name: Servais Verherstraeten
                        politician_id: politician_be_232
                      - key: nahima_lanjri
                        name: Nahima Lanjri
                        politician_id: politician_be_142
                      - key: walter_schroons
                        name: Walter Schroons
                        politician_id: politician_be_142
  /gps/campaign/{key}:
    get:
      summary: a poll campaign
      tags: [poll]
      parameters:
        - $ref: '#/components/parameters/key'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/poll_campaign"
              examples:
                default:
                  value:
                    key: 2018_be_district
  /gps/poll/{key}:
    get:
      summary: a poll, related survey and segments
      tags: [poll]
      parameters:
        - $ref: '#/components/parameters/key'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/poll"
              examples:
                default:
                  value:
                    key: 2018_be_district_6850
                    survey_key: 2018_be_district_wallonia_rural
                    segment_key: 2018_be_district_6850
  /gps/survey/{key}:
    get:
      summary: a survey and related questions
      tags: [survey]
      parameters:
        - $ref: '#/components/parameters/key'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/survey"
              examples:
                compatibility:
                  value:
                    key: be_brussels_2014
                    name: survey_be_brussels_2014
                    question_order:
                      - question_2
                      - question_6
                    questions:
                      - key: question_2
                        text: question_2_text
                        answer_format: agr_5_scale_tol_3_scale_abs
                      - key: question_6
                        text: question_6_text
                        notice: question_6_notice
                        answer_format: agr_5_scale_tol_3_scale_abs
                    answer_formats: &answerFormat
                      - key: agr_5_scale_tol_3_scale_abs
                        items:
                          - key: fully_agree
                            name: answer_format_item_fully_agree
                            weight: 100
                          - key: rather_yes
                            name: answer_format_rather_yes
                            weight: 75
                          - key: no_opinion
                            name: answer_format_item_no_opinion
                            weight: 50
                          - key: rather_no
                            name: answer_format_item_rather_no
                            weight: 25
                          - key: strongly_disagree
                            name: answer_format_item_strongly_disagree
                            weight: 0
                        tolerance:
                          absolute: true
                          items:
                            - key: very_important
                              name: answer_format_tolerance_item_very_important
                              weight: 2.5
                            - key: important
                              name: answer_format_tolerance_item_important
                              weight: 1
                            - key: not_important
                              name: answer_format_tolerance_item_not_important
                              weight: 0.4
                    i18n:  
                      en:
                        question_2_text: Regions should manage their social security systems independently
                        question_6_text: Les Régions devraient gérer de façon autonome leur sécurité sociale
                        question_6_notice: |
                          Dans le cadre de la 6° réforme de l’Etat, la totalité des recettes d’une branche de la sécurité sociale -les allocations familiales - sera transféré aux trois Régions et à la Communauté germanophone. 
                          Dans la Région de Bruxelles-Capitale, le transfert aura lieu à la Commission communautaire commune dont relève l’ensemble des francophones et des néerlandophones y domiciliés. 
                          Chaque entité pourra adopter sa propre clef de répartition et fixera, de manière autonome, ses critères de répartition en fonction des objectifs de sa politique familiale. 
                          L’ensemble des cotisations sociales (y compris celles relatives aux allocations familiales) à charges des entreprises ou des travailleurs indépendants restent, pour leur fixation et leur collecte, du ressort de l’Etat fédéral. 
                          Ceci pour éviter des différences dans les taux des cotisations sociales pouvant influencer le choix de localisation des entreprises sur base d’une surenchère entre les Régions.
                        answer_format_item_fully_agree: Fully agree # factorise this
                        answer_format_item_rather_yes: Rather yes
                        answer_format_item_no_opinion: No opinion
                        answer_format_item_rather_no: Rather no
                        answer_format_item_strongly_disagree: Strongly disagree
                        answer_format_tolerance_absolute: Absolute
                        answer_format_tolerance_item_very_important: Very important
                        answer_format_tolerance_item_important: Important
                        answer_format_tolerance_item_not_important: Not important
                2014_be_regional:
                  value:
                    key: 2014_be_regional
                    name: survey_2014_be_regional
                    answer_formats: *answerFormat   
                    question_order:
                      - legal_retirement_age_should_be_increased_65_to_67
                      - turkey_may_join_eu
                    questions:
                      - key: legal_retirement_age_should_be_increased_65_to_67
                        notice: Some notice
                        answer_format: agr_5_scale_tol_3_scale_abs
                      - key: turkey_may_join_eu
                        notice: Some notice
                        answer_format: agr_5_scale_tol_3_scale_abs
                    i18n:
                      fr:
                        survey_2014_be_regional: Elections régionales 2014    
                      en:
                        question_legal_retirement_age_should_be_increased_65_to_67: The legal retirement age should be increased from 65 to 67 years.    
                        question_turkey_may_join_eu: Turkey may join the European Union.
                        answer_format_item_fully_agree: Fully agree
                        answer_format_item_rather_yes: Rather yes
                        answer_format_item_no_opinion: No opinion
                        answer_format_item_rather_no: Rather no
                        answer_format_item_strongly_disagree: Strongly disagree
                        answer_format_tolerance_absolute: Absolute
                        answer_format_tolerance_item_very_important: Very important
                        answer_format_tolerance_item_important: Important
                        answer_format_tolerance_item_not_important: Not important
                default:
                  value:
                    key: 2018_be_district_wallonia_rural
                    questions_order:
                      - should_social_care_be_private
                      - should_watching_the_red_devils_be_mandatory
                    questions: 
                      - key: should_social_care_be_private
                      - key: should_watching_the_red_devils_be_mandatory
  /gps/submission:
    post:
      summary: submit answers
      tags: [answer]
      requestBody:
        content:
          application/json:     
            schema:
              $ref: "#/components/schemas/submission"
            examples:
              default:
                value:                  
                  poll_key: 2018_be_district_6850
                  survey_key: 2018_be_district_wallonia_rural
                  segment_key: 2018_be_district_6850
                  answers: 
                    - value: strongly_no
                      tolerance: important
                      question_key: should_social_care_be_private
                    - value: rather_yes
                      tolerance: not_important
                      question_key: should_watching_the_red_devils_be_mandatory
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/submission"
  /gps/match:
    post:
      summary: match answers
      tags: [match]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/match"
            examples:
              default:
                value:
                  segment_key: 2018_be_district_6850_candidates
                  answers: 
                    - value: strongly_no
                      tolerance: important
                      question_key: should_social_care_be_private
                    - value: rather_yes
                      tolerance: not_important
                      question_key: should_watching_the_red_devils_be_mandatory
      responses:
        '200':
          description: success
components:
  headers:
    Accept-Language:
      description: The languages for i18n
      schema:
        type: string
  parameters:
    key:
      name: key
      required: true          
      in: path
      schema:
        type: string
    district_key:
      name: district_key
      required: true          
      in: path
      schema:
        type: string
    election_key:
      name: election_key      
      in: query
      schema:
        type: string
  schemas:
    i18n:
      type: object
      description: scoped translations
      properties:
        nl:
          type: object
        fr:
          type: object
        de:
          type: object
    election:
      type: object
      description: an election [main or district] with parties and candidates
      required:
        - key
      properties:
        key: 
          $ref: '#/components/parameters/key' # TODO should have path parameter and normal ones
        type:
          type: string
          enum: [be_federal_chamber_of_representatives]
        main_election_key:
          type: string
        district_type:
          type: string
          enum: [province, municipality]
        district_key: 
          $ref: '#/components/parameters/district_key'
        date: # or date ?? 2018-06 -> is ISO valid
          type: string
          format: date
        active: 
          type: boolean
        parties:
          type: array
          items:
            $ref: '#/components/schemas/election_party'
        candidates:
          type: array
          items:
            $ref: '#/components/schemas/candidate'
        i18n:
          $ref: '#/components/schemas/i18n'
    election_party:
      type: object
      description: an election party with members
      properties:
        key:
          type: string
        name:
          type: string
        candidates:
          type: array
          items:
            $ref: '#/components/schemas/election_party_candidate'
        substitutes:
          type: array
          items:
            $ref: '#/components/schemas/election_party_candidate'
    election_party_candidate:
      type: object
      description: an election party member
      properties:
        order:
          type: integer
        key:
          type: string
    candidate: # they use election_roll
      type: object
      description: an election candidate
      properties:
        key:
          type: string
        name:
          type: string    
        picture:
          type: string # maybe URI is possible   
        politician_id:
          type: string
        politician_url:
          type: string
    candidate_search_response:
      type: object
      properties:
        start:
          type: integer
        limit:
          type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/candidate'
    party_search_response:
      type: object
      properties:
        start:
          type: integer
        limit:
          type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/election_party'
    district:
      type: object
      description: an election district
      properties:
        key:
          type: string
        postcode:
          type: string
        i18n:
          $ref: '#/components/schemas/i18n'
    poll_campaign:
      type: object
      description: a poll campaign
      properties:
        key: 
          $ref: '#/components/parameters/key'
    poll:
      type: object
      description: a poll
      properties:
        key: 
          $ref: '#/components/parameters/key'
        survey_key: 
          type: string
        segment_key:
          type: string
    survey:
      type: object
      description: a survey with questions
      properties:
        key: 
          $ref: '#/components/parameters/key'
        answer_formats:
          type: array
          items:
            $ref: '#/components/schemas/answer_format'
        questions_order:
          type: array
          items:
            type: string
        questions:
          type: array
          items:
            $ref: '#/components/schemas/question'
        i18n:
          $ref: '#/components/schemas/i18n'
    question:
      type: object
      description: a question
      properties:
        key:
          type: string
        # there is a name and an explanation/notice [excerpt ??]
    answer_format:
      type: object
      description: an answer format
      properties:
        key: 
          $ref: '#/components/parameters/key'
        items:
          type: array
          items:
            $ref: '#/components/schemas/answer_format_item'
        tolerance:
          $ref: '#/components/schemas/answer_format_tolerance'
    answer_format_tolerance:
      type: object
      properties:
        absolute:
          type: boolean
        items:
          type: array
          items:
            $ref: '#/components/schemas/answer_format_item'
    answer_format_item:
      type: object    
      properties:
        key: 
          $ref: '#/components/parameters/key' # trouble with this in swagger_uis
        name:
          type: string
        weight:
          type: integer # TODO find format for double 
    submission:
      type: object
      description: answers submission
      properties:
        id:
          readOnly: true
          type: string
          format: uuid
        time:
          readOnly: true
          type: string
          format: datetime
        poll_key:
          type: string
        survey_key:
          type: string
        segment_key:
          type: string
        answers:
          type: array
          items:
            $ref: '#/components/schemas/answer'
    answer:
      type: object
      description: an answer
      properties:
        value:
          type: string
        tolerance:
          type: string
        question_key:
          type: string
    match:
      type: object
      description: answers match submission
      properties:
        segment_key:
          type: string
        answers:
          type: array
          items:
            $ref: '#/components/schemas/answer'
